trigger:
- main

variables:
  buildProgramFilePath: 'sample_markdown/build_program'
  buildProgramFileName: 'md-to-html.js'
  targetMarkdownRelativePath: '../sample'

jobs:
- job: HtmlBuild
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - script: |
        cd $(buildProgramFilePath)
        yarn add crossnote
      displayName: 'crossnote install'

    - script: |
        apt install -y libtool graphviz
      displayName: 'graphviz install'

    - script: |
        cd $(buildProgramFilePath)
        node $(buildProgramFileName) $(targetMarkdownRelativePath).md
      # cp $(targetMarkdownRelativePath).html $(Build.ArtifactStagingDirectory)/
      displayName: 'markdown document build'

    - task: publishBuildArtifacts@1
      displayName: 'Publish Artifact: crossnote'