# markdownの変換を行う

variables:
  buildProgramFilePath: 'markdown/build_program/md-to-html.js'
  targetMarkdownFilePath: 'markdown/sample'

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

# crossnoteのインストール
- script: |
    yarn add crossnote
  displayName: 'crossnote install'

# graphvizのインストール
- script: |
    sudo apt update
    sudo apt install -y libtool graphviz
  displayName: 'Graphviz install'

# markdownの変換
- script: node $(buildProgramFilePath)  $(System.DefaultWorkingDirectory)/$(targetMarkdownFilePath).md
  displayName: 'Markdown document build'

# ビルドしたファイルを公開するフォルダにコピー
- task: CopyFiles@2
  inputs:
    Contents: '$(targetMarkdownFilePath).html'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy files'

# ビルド成果物をアップロードする
- task: publishBuildArtifacts@1
  displayName: 'Publish artifact'