# markdownの変換を行う

variables:
  documentPath: 'markdown'
  buildProgramFilePath: 'markdown/build_program/md-to-html.js'
  targetMarkdownFileName: 'markdown/sample'

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

# crossnoteのインストール
- script: |
    cd $(buildProgramFilePath)
    yarn add crossnote
  displayName: 'crossnote install'

# graphvizのインストール
- script: |
    sudo apt update
    sudo apt install -y libtool graphviz
  displayName: 'Graphviz install'

# markdownの変換
- script: |
    cd $(documentPath)
    node $(Pipeline.Workspace)/$(buildProgramFilePath) $(Pipeline.Workspace)/$(targetMarkdownFileName).md
  displayName: 'Markdown document build'

- script: ls $(documentPath)

# ビルドしたファイルを公開するフォルダにコピー
- task: CopyFiles@2
  inputs:
    Contents: '$(documentPath)/$(targetMarkdownFileName).html'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/$(documentPath)'
  displayName: 'Copy files'

# ビルド成果物をアップロードする
- task: publishBuildArtifacts@1
  displayName: 'Publish artifact'
