# markdownの変換を行う

variables:
  documentPath: 'markdown'
  buildProgramFilePath: 'build_program/md-to-html.js'
  targetMarkdownFileName: 'sample'

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

# crossnoteのインストール
- script: |
    yarn add crossnote
  displayName: 'crossnote install'

# graphvizのインストール
- script: |
    sudo apt update
    sudo apt install -y libtool graphviz
  displayName: 'Graphviz install'

# markdownの変換
- script: node $(documentPath)/$(buildProgramFilePath) $(Agent.HomeDirectory)/$(documentPath)/$(targetMarkdownFileName).md
  displayName: 'Markdown document build'

# ビルドしたファイルを公開するフォルダにコピー
- task: CopyFiles@2
  inputs:
    Contents: '$(documentPath)/$(targetMarkdownFileName).html'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy files'

# ビルド成果物をアップロードする
- task: publishBuildArtifacts@1
  displayName: 'Publish artifact'
