# markdownの変換を行う

variables:
  buildProgramFilePath: 'markdown/build_program'
  buildProgramFileName: 'md-to-html.js'
  targetMarkdownRelativePath: '../sample'

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

# crossnoteのインストール
- script: |
    cd $(buildProgramFilePath)
    yarn add crossnote
  displayName: 'crossnote install'

# graphvizのインストール
- script: |
    sudo apt update
    sudo apt install -y libtool graphviz
  displayName: 'Graphviz install'

# markdownの変換
- script: |
    cd $(buildProgramFilePath)
    node $(buildProgramFileName) $(targetMarkdownRelativePath).md
  displayName: 'Markdown document build'

- script: ls $(buildProgramFilePath)/../

# ビルドしたファイルを公開するフォルダにコピー
- task: CopyFiles@2
  inputs:
    Contents: '$(buildProgramFilePath)/$(targetMarkDownRelativePath).html'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/$(folderName)'
  displayName: 'Copy files'

# ビルド成果物をアップロードする
- task: publishBuildArtifacts@1
  displayName: 'Publish artifact'
