trigger:
- main

variables:
  buildProgramFilePath: 'markdown/build_program'
  buildProgramFileName: 'md-to-html.js'
  targetMarkdownRelativePath: '../sample'

jobs:
- job: HtmlBuild
  pool:
    vmImage: 'macOS-13'
  steps:
    - script: |
        cd $(buildProgramFilePath)
        yarn add crossnote
      displayName: 'crossnote install'

    - script: |
        brew install libtool
        brew link libtool
        brew install graphviz
        brew link --overwrite graphviz
      displayName: 'graphviz install'

    - script: |
        brew install icu4c
        cd $(buildProgramFilePath)
        node $(buildProgramFileName) $(targetMarkdownRelativePath).md
        ls ..
      # cp $(targetMarkdownRelativePath).html $(Build.ArtifactStagingDirectory)/
      displayName: 'markdown document build'

    - task: publishBuildArtifacts@1
      displayName: 'Publish Artifact: crossnote'