# pythonファイルのpytestとpyinstallerビルドを行う

variables:
  specFilePath: 'python\pyinstaller.spec'
  buildExeName: 'sample.exe'

trigger:
- main

jobs:
- job: PytestExec
  pool:
    vmImage: 'windows-latest'
  steps:

    # 用いるpythonのバージョンを指定
    - task: 'UsePythonVersion@0'
      inputs:
        versionSpec: '3.11'

    # pytestのpip installを行う
    - script: pip install pytest
      displayName: pipInstall

    # pytestを実施する
    - script: |
        cd python
        pytest -vv -s
      displayName: py test

- job: PyinstallerBuildWindows
  # PyTestExecジョブがsucceededで完了したときに実行される
  dependsOn: PyTestExec
  condition: succeeded()
  pool:
    vmImage: 'Windows-latest'
  steps:

    - task: 'UsePythonVersion@0'
      inputs:
        versionSpec: '3.11'

    # pyinstallerのpip installを行う
    - script: pip install pyinstaller
      displayName: pipInstall

    # pyinstallerのビルドを行う
    - script: pyinstaller $(specFilePath)
      displayName: pyinstaller build

    # 成果物をアップロード用フォルダにコピーする
    - script: |
        xcopy "dist\(buildExeName)" "$(Build.ArtifactStagingDirectory)"
      displayName: CopyTargetFolder

    # ビルド成果物をアップロードする
    - task: publishBuildArtifacts@1
      displayName: 'Publish artifact'
