# pythonファイルのpytestとpyinstallerビルドを行う

# 変数定義
variables:
  specFilePath: 'python\src\pyinstaller.spec'
  buildExePath: '\dist\sample.exe'

# mainブランチが更新されたときに起動
trigger:
- main

# jobsを呼び出すことで複数の処理(job)を実行することができる。
jobs:
- job: PytestExec
  # windows OS で実行
  pool:
    vmImage: 'windows-latest'

  # steps内に実行する処理を記述する
  steps:

    # task「UsePythonVersion@0」を用いてpythonのバージョンを指定
    - task: 'UsePythonVersion@0'
      inputs:
        versionSpec: '3.11'

    # pytestのpip installを行う
    - script: pip install pytest
      displayName: pipInstall

    # pytestを実施する
    - script: |
        cd python
        pytest -vv -s
      displayName: py test

- job: PyinstallerBuildWindows
  # PyTestExecジョブがsucceededで完了したときに実行される
  dependsOn: PyTestExec
  condition: succeeded()
  # windows OS で実行
  pool:
    vmImage: 'Windows-latest'

  # steps内に実行する処理を記述する
  steps:

    # task「UsePythonVersion@0」を用いてpythonのバージョンを指定
    - task: 'UsePythonVersion@0'
      inputs:
        versionSpec: '3.11'

    # pyinstallerのpip installを行う
    - script: pip install pyinstaller
      displayName: pipInstall

    # pyinstallerのビルドを行う
    - script: pyinstaller $(specFilePath)
      displayName: pyinstaller build

    # task「CopyFiles@2」を用いて必要ファイルのコピーを行う
    - task: CopyFiles@2
      inputs:
        contents: '$(buildExePath)'
        targetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Copy file'

    # task「publishBuildArtifacts@1」を用いてビルド成果物をアップロードする
    - task: publishBuildArtifacts@1
      displayName: 'Publish artifact'