# doxygenのビルドを行う

variables:
  folderName: 'doxygen'
  indexFileName: 'doxygen_view.html'

trigger:
- main

pool:
  vmImage: 'Ubuntu-latest'

steps:

# doxygenのインストール
- script: 'sudo apt install -y doxygen'
  displayName: 'Install doxygen'

# doxygenのビルド
- script: |
    cd $(folderName)
    doxygen Doxyfile
  displayName: 'Run doxygen'

# ビルドしたファイルを公開するフォルダにコピー
- task: CopyFiles@2
  contents: '$(folderName)/latex/**'
  targetFolder: '$(Build.ArtifactStagingDirectory)/latex'
  displayName: 'Copy files 1'

- task: CopyFiles@2
  contents: '$(folderName)/html/**'
  targetFolder: '$(Build.ArtifactStagingDirectory)/html'
  displayName: 'Copy files 2'

- task: CopyFiles@2
  contents:  '$(folderName)/$(indexFileName)'
  targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy files 3'

# ビルド成果物をアップロードする
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'
