# doxygenのビルドを行う

# 変数定義
variables:
  folderName: 'doxygen/docs'
  indexFileName: 'doxygen_view.html'

# mainブランチが更新されたときに起動
trigger:
- main

# ubuntu OS で実行
pool:
  vmImage: 'Ubuntu-latest'

# steps内に実行する処理を記述する
steps:

# doxygenのインストール
- script: 'sudo apt install -y doxygen'
  displayName: 'Install doxygen'

# doxygenのビルド
- script: |
    cd $(folderName)
    doxygen Doxyfile
  displayName: 'Run doxygen'

# task「CopyFiles@2」を用いて必要ファイルのコピーを行う
- task: CopyFiles@2
  inputs:
    contents: '$(folderName)/latex/**'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy files 1'

- task: CopyFiles@2
  inputs:
    contents: '$(folderName)/html/**'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy files 2'

- task: CopyFiles@2
  inputs:
    contents:  '$(folderName)/$(indexFileName)'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy files 3'

# task「publishBuildArtifacts@1」を用いてビルド成果物をアップロードする
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'